### ISSUE TITLE
fails to build on Mac with homebrew

### ISSUE THREAD

**Issue by agarwal** [savonet/ocaml-ssl#30]
```bash
$ opam depext ssl
# Detecting depexts using flags: x86_64 osx homebrew
# The following system packages are needed:
#  - openssl
#  - pkg-config
# All required OS packages found.
```

```bash
$ opam install ssl
The following actions will be performed:
  ∗  install ssl 0.5.3

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] The compilation of ssl failed at "sh -exc ./configure --prefix /Users/ashish/.opam/4.03.0 CPPFLAGS=\"$CPPFLAGS
        -I/opt/local/include -I/usr/local/opt/openssl/include\"".

#=== ERROR while compiling ssl.0.5.3 ==========================================#
# command      sh -exc ./configure --prefix /Users/ashish/.opam/4.03.0 CPPFLAGS="$CPPFLAGS -I/opt/local/include -I/usr/local/opt/openssl/include"
...
# checking for SSL_new in -lssl... no
# configure: error: Cannot find libssl.
```

When you do `brew install openssl`, it informs you that Apple has deprecated openssl, and so homebrew refuses to create symlinks within `/usr/local`. To use openssl, it suggests to add the flags `-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib`. So I noticed that the `-I` flag is handled by this project's opam file, but the `-L` flag isn't.

**Comment by agarwal** [comment]
Also, would it be possible to support Apple's SSL library instead given openssl is not recommended anymore.

**Comment by agarwal** [comment]
This works:
```LDFLAGS=-L/usr/local/opt/openssl/lib opam install ssl```

**Comment by agarwal** [comment]
On another Mac that we believe is configured the same (same version of XCode, same version of OS X), the package installed just fine. So not sure exactly what the issue is on my laptop.

**Comment by jagare** [comment]
I've got the same problem on OSX 10.11. Solved with this line
`export EXTRA_CFLAGS=-I/usr/local/opt/openssl/include && export EXTRA_CXXFLAGS=-I/usr/local/opt/openssl/include & export EXTRA_LDFLAGS=-L/usr/local/opt/openssl/lib & opam install ssl`

**Comment by jagare** [comment]
Actually above didn't work for some reason (from the configure.log it was obvious EXTRA_LDFLAGS didn't get into the check for libssl). However the following worked on my machine
`export CPPFLAGS=-I/usr/local/opt/openssl/include
 export LDFLAGS=-L/usr/local/opt/openssl/lib
opam install ssl
 `

**Comment by toots** [comment]
This seems to have been added to the `opam` package. I'm closing here since it is an `opam` issue. Feel free to open an issue with them if you still see an issue and link @smimram or myself in it. Thanks!

**Comment by samoht** [comment]
@toots Can you clarify what is the fix? This is still broken for me:

```
#=== ERROR while installing ssl.0.5.3 =========================================#
# opam-version 1.2.2
# os           darwin
# command      sh -exc ./configure --prefix /Users/thomas/.opam/ssl CPPFLAGS="$CPPFLAGS -I/opt/local/include -I/usr/local/opt/openssl/include"
# path         /Users/thomas/.opam/ssl/build/ssl.0.5.3
# compiler     system (4.04.0)
# exit-code    1
# env-file     /Users/thomas/.opam/ssl/build/ssl.0.5.3/ssl-39582-03b1a4.env
# stdout-file  /Users/thomas/.opam/ssl/build/ssl.0.5.3/ssl-39582-03b1a4.out
# stderr-file  /Users/thomas/.opam/ssl/build/ssl.0.5.3/ssl-39582-03b1a4.err
### stdout ###
# [...]
# checking for ocamldep... /usr/local/bin/ocamldep
# checking for ocamllex... /usr/local/bin/ocamllex
# checking for ocamlyacc... /usr/local/bin/ocamlyacc
# checking for ocamldoc... /usr/local/bin/ocamldoc
# checking for ocamlmktop... /usr/local/bin/ocamlmktop
# checking for gcc... (cached) gcc
# checking whether we are using the GNU C compiler... (cached) yes
# checking whether gcc accepts -g... (cached) yes
# checking for gcc option to accept ISO C89... (cached) none needed
# checking for SSL_new in -lssl... no
### stderr ###
# + ./configure --prefix /Users/thomas/.opam/ssl 'CPPFLAGS= -I/opt/local/include -I/usr/local/opt/openssl/include'
# configure: error: Cannot find libssl.
```

**Comment by agarwal** [comment]
> I'm closing here since it is an `opam` issue.

The package fails to install without opam too. If anything, the opam file has provided a partial fix that should be upstreamed into this repo. And ideally an `opam` file would be added to this repo.

**Comment by toots** [comment]
@samoht, I'd imagine that you have `openssl` installed from `homebrew`, right?

@agarwal, I think I disagree here. `ocaml-ssl` makes reasonable assumptions about where to search for that header. `homebrew`'s headers are decisively placed in a location that isn't in the way of most build systems:
```
This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
    PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig
```

**Comment by agarwal** [comment]
> `ocaml-ssl` makes reasonable assumptions about where to search for that header.

Homebrew has become the de facto standard package manager on Mac, so it would help to extend the definition of "reasonable assumptions" to include whatever homebrew does.

However, I'm not even sure using openssl on a Mac is the correct choice any longer. As I asked above, should this package instead bind against Apple's alternative ssl library. I know nothing about ssl libs, so maybe that's not even possible.

**Comment by toots** [comment]
`ocaml-ssl` is just what it is, a binding to `libssl`. A Apple-specific bindings against their own crypto library could be a nice, though, but it'd be a different project. Could be a good one to do with `cstruct`, too!

**Comment by agarwal** [comment]
> Apple-specific bindings against their own crypto library could be nice, though, but it'd be a different project.

I see. I thought perhaps the Apple lib has a compatible API. I though it might because otherwise isn't every software on a Mac having to be rewritten.

**Comment by samoht** [comment]
Note: my issue has been fixed by running `xcode-select --install` as @avsm pointed out on https://github.com/mirage/ocaml-cohttp/issues/512#issuecomment-275650814

**Comment by agarwal** [comment]
@samoht Thanks! That resolves the problem for me too. A plain `opam install ssl` now works.

**Comment by FranklinChen** [comment]
I just ran into this problem that `opam install ssl` fails for me because I don't link `openssl` in Homebrew. I had to use https://github.com/savonet/ocaml-ssl/issues/30#issuecomment-262282789 by going

```
$ LDFLAGS=-L/usr/local/opt/openssl/lib opam install ssl
```

Unfortunately, it's confusing to me that this failure happened when I was installing some random other package.

**Comment by agarwal** [comment]
@FranklinChen Did you try `xcode-select --install`. For me and others, once we did this, a plain `opam install ssl` worked.

>  it's confusing to me that this failure happened when I was installing some random other package.

Well, if that package depends on `ssl`, then this package will have to get installed. That's normal.

**Comment by FranklinChen** [comment]
Ah, `xcode-select` fixed it!
